### ISSUE TITLE
Parser fails when unbox syntax is used

### ISSUE THREAD

**Issue by MSleepyPanda** [shepmaster/fuzzy-pickles#93]
Example

```rust
pub fn unbox(box f: Box<Foo>) {}
```

This is valid rust code on nightly, though feature gated. I couldn't really find information whether you want to support nightly features. 

I'd be happy to work on this, given that you can give guidance on where to start!

**Comment by shepmaster** [comment]
Wonderful, thank you for finding that. To be honest, I wasn't even aware of such a syntax! 😊 

It looks like it's a type of pattern syntax and the error message seems to agree: `box pattern syntax is experimental (see issue #29641)`, thus I'd suggest the following path:

1. Add a test [in the pattern section](https://github.com/shepmaster/fuzzy-pickles/blob/d729873e72b3393c67fe7cdcd691cc45dfbf5f17/src/lib.rs#L5522-L5719)

1. Add a new [`PatternKind`](https://github.com/shepmaster/fuzzy-pickles/blob/d729873e72b3393c67fe7cdcd691cc45dfbf5f17/src/lib.rs#L1620-L1634); i'd suggest calling it `Box`.

1. Update [`pattern_kind`](https://github.com/shepmaster/fuzzy-pickles/blob/d729873e72b3393c67fe7cdcd691cc45dfbf5f17/src/lib.rs#L3480-L3498); following the structure of [`pattern_reference`](https://github.com/shepmaster/fuzzy-pickles/blob/d729873e72b3393c67fe7cdcd691cc45dfbf5f17/src/lib.rs#L3598-L3610) should be close.
